language: python
python:
- '2.7'
before_script:
- cd ..
- wget http://googleappengine.googlecode.com/files/google_appengine_1.8.2.zip
- unzip google_appengine_1.8.2.zip
- rm google_appengine_1.8.2.zip
- ln -s google_appengine/*.py .
- sudo apt-get install python-imaging
install:
- "pip install -r requirements.txt --use-mirrors"
script:
- git clone https://github.com/andrewbeng89/python-gae-demo.git deploy
after_success:
- google_appengine/appcfg.py --oauth2_refresh_token=$MY_GAE_TOKEN update deploy/