application: mitb-python-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application
  
- url: /public
  static_dir: public
  
libraries:
- name: PIL
  version: latest