application: mitb-python-demo
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html
  
- url: /api/.*
  script: helloworld.application
  
libraries:
- name: PIL
  version: latest